### ISSUE TITLE
Resize filesystem of a larger volume created from a snapshot/volume

### ISSUE THREAD

**Issue by RomanBednar** [openshift/ovirt-csi-driver#106]
Upstream [issue](https://github.com/kubernetes/kubernetes/issues/94929) introduces improvements to volume resizing. The change added new resize code and moved to [kubernetes/mount-utils](https://github.com/kubernetes/mount-utils). 

This change should be reflected in all CSI drivers. New module should be imported and it's resize logic added. 

Dependency should be updated to use the current k8s/mount-utils module and CSI driver should use the resize code it provides in NodeStageVolume to perform the resize if needed. Example of similar change can be found [here](https://github.com/kubernetes/cloud-provider-openstack/pull/1563/files)

Issue originated in [BZ1877261](https://bugzilla.redhat.com/show_bug.cgi?id=1877261)

#### How to reproduce:
1. create original pod and pvc
2. create snapshot from original pvc
3. create pvc from the snapshot specifying larger size than the original
4. create pod to consume the new pvc
5. observe fs size of the new volume inside the pod does not match the requested size

**Comment by RomanBednar** [comment]
Hello, any updates on this one? Can we expect a fix in foreseeable future?

/assign @rgolangh

**Comment by rgolangh** [comment]
@sandrobonazzola we need to update the owners here. please advice

**Comment by RomanBednar** [comment]
Ack, I must have looked at upstream owners file when commenting: https://github.com/oVirt/csi-driver/blob/master/OWNERS

**Comment by RomanBednar** [comment]
@engelmi checking back on the issue after it's been assigned to you. Do you intend to work on this issue? If so, when can we expect the fix to land?

**Comment by RomanBednar** [comment]
Checking the code it appears that driver does not support snapshots atm, please confirm that this feature is not supported and feel free to close this issue.

https://github.com/openshift/ovirt-csi-driver/blob/cb069cdedddcb4cf75b2a3c4dc4f8bd345969726/pkg/service/controller.go#L272

**Comment by engelmi** [comment]
Hi @RomanBednar, sorry for the late reply. 
You are right, snapshots are currently not supported and, unfortunately, it is also not on our roadmap to implement this feature for 4.12 due to reduced capacity on our side (as RHV as a host platform will be deprecated, see [release notes 4.11](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-rhv-deprecations)).
